---
- name: "Ansible configuration file for manage containerization the project with docker"
  hosts: localhost 
  vars: 
    docker_images:
      - { name: "devops-tutorial-app", tag: "latest" }
      - { name: "mongo", tag: "5.0" }

  tasks:
    - name: "Ensure Docker service is started"
      service: 
        name: docker 
        state: started
        enabled: yes
    - name: "Stop & Delete Docker containers using docker-compose"
      community.docker.docker_compose_v2:
        project_src: .
        state: absent 

    - name: "Build & Run Docker containers using docker-compose"
      community.docker.docker_compose_v2:
        project_src: .
        state: present
        build: always   

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"

    - name: "Tag Docker images"
      loop: "{{ docker_images }}"
      ansible.builtin.shell:
        cmd: "docker tag {{ item.name }}:{{ item.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/{{ item.name }}:{{ item.tag }}"

    - name: "Push Docker images to Docker Hub"
      loop: "{{ docker_images }}"
      ansible.builtin.shell:
        cmd: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/{{ item.name }}:{{ item.tag }}"

    - name: Log out from Docker Hub
      ansible.builtin.shell:
        cmd: "docker logout"
        