apiVersion: v1
kind: Service
metadata:
  name: mongo-service  # Specify a name for your service
  labels:
    app: mongo
spec:
  selector:
    app: mongo  # This should match the label of the MongoDB deployment
  ports:
    - protocol: TCP
      port: 27017  # External port of the service
      targetPort: 27017  # Port inside the MongoDB container
  type: ClusterIP  # This exposes the service internally within the Kubernetes cluster
